[supervisord]
nodaemon=true
user=root

[program:backend]
directory=/app
command=/root/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8001 --workers 1 --reload
autostart=true
autorestart=true
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend.err.log
environment=SECRET_KEY="%(ENV_SECRET_KEY)s",DATABASE_URL="%(ENV_DATABASE_URL)s",GEMINI_API_KEY="%(ENV_GEMINI_API_KEY)s"

[program:frontend]
directory=/app/frontend
command=yarn start
autostart=true
autorestart=true
stdout_logfile=/var/log/frontend.log
stderr_logfile=/var/log/frontend.err.log
