"""add_variant_to_vehicles

Revision ID: cd8c1207ce67
Revises: 0021_refresh_tokens
Create Date: 2026-02-26 15:20:38.978548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8c1207ce67'
down_revision = '0021_refresh_tokens'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('variant', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'variant')
    # ### end Alembic commands ###
